# Generated by Django 4.2.20 on 2025-04-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory_app.division'),
            preserve_default=False,
        ),
    ]
