# Generated by Django 4.2.16 on 2025-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory_app", "0002_organization_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_person_name",
            field=models.CharField(max_length=255),
        ),
    ]
