# Generated by Django 4.2.16 on 2025-04-14 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directory_app", "0003_alter_organization_contact_person_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="designation",
        ),
    ]
