# Generated by Django 4.2.20 on 2025-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0004_remove_organization_contact_person_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylist',
            old_name='address',
            new_name='about_company',
        ),
        migrations.RenameField(
            model_name='companylist',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='companylist',
            old_name='phone',
            new_name='mobile3',
        ),
        migrations.RemoveField(
            model_name='companylist',
            name='division',
        ),
        migrations.AddField(
            model_name='companylist',
            name='email2',
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companylist',
            name='email3',
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companylist',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylist',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylist',
            name='social_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylist',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
