# Generated by Django 4.2.20 on 2025-04-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0005_rename_address_companylist_about_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylist',
            old_name='email',
            new_name='email1',
        ),
    ]
