# Generated by Django 4.2.20 on 2025-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0006_rename_email_companylist_email1'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
