# Generated by Django 3.2.18 on 2025-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0007_companylist_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PoliticalIdentity',
                'verbose_name_plural': 'PoliticalIdentitys',
                'db_table': 'political_identity',
            },
        ),
    ]
