# Generated by Django 3.2.18 on 2025-04-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0008_politicalidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory_app.companylist'),
        ),
        migrations.AddField(
            model_name='personlist',
            name='political_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory_app.politicalidentity'),
        ),
        migrations.AlterField(
            model_name='personlist',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory_app.designation'),
        ),
        migrations.AlterField(
            model_name='personlist',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory_app.organization'),
        ),
        migrations.AlterField(
            model_name='personlist',
            name='person_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory_app.personlevel'),
        ),
    ]
