# Generated by Django 3.2.18 on 2025-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0009_auto_20250417_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlist',
            name='facebook_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personlist',
            name='linkedin_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personlist',
            name='twitter_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
